"use client";

import { useEffect, useState } from "react";

import { api } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PageHeader, EmptyState } from "@/components/page-header";
import type { ContentIdea } from "@/types";

export default function ContentPage() {
  const [ideas, setIdeas] = useState<ContentIdea[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api
      .content()
      .then(setIdeas)
      .catch((e) => setError((e as Error).message));
  }, []);

  return (
    <>
      <PageHeader
        title="Content Ideas"
        description="TikTok content generated by the Content Creator agent."
      />
      {error ? (
        <div className="mb-6 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      ) : null}
      {ideas.length === 0 && !error ? (
        <EmptyState message="No content ideas yet. Run the content pipeline workflow." />
      ) : (
        <div className="space-y-4">
          {ideas.map((c) => (
            <Card key={c.id}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">{c.title}</CardTitle>
                  <Badge variant="muted">{c.status}</Badge>
                </div>
                <CardDescription>{c.hook}</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="mb-3 text-sm">{c.caption}</p>
                <div className="flex flex-wrap gap-2">
                  {c.hashtags.map((h) => (
                    <Badge key={h}>{h}</Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </>
  );
}
