"""add_photos_viewed_to_video_metrics

Revision ID: 3c46fe6af036
Revises: f60626417a25
Create Date: 2026-07-15 16:39:06.412839
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3c46fe6af036'
down_revision = 'f60626417a25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metrics', sa.Column('photos_viewed', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_video_metrics_video_id'), table_name='video_metrics')
    op.create_index(op.f('ix_video_metrics_video_id'), 'video_metrics', ['video_id'], unique=True)
    op.drop_index(op.f('ix_video_uploads_video_id'), table_name='video_uploads')
    op.create_index(op.f('ix_video_uploads_video_id'), 'video_uploads', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_uploads_video_id'), table_name='video_uploads')
    op.create_index(op.f('ix_video_uploads_video_id'), 'video_uploads', ['video_id'], unique=False)
    op.drop_index(op.f('ix_video_metrics_video_id'), table_name='video_metrics')
    op.create_index(op.f('ix_video_metrics_video_id'), 'video_metrics', ['video_id'], unique=False)
    op.drop_column('video_metrics', 'photos_viewed')
    # ### end Alembic commands ###
