"""multi_upload_support_for_carousel

Revision ID: 97e57bca510f
Revises: 3c46fe6af036
Create Date: 2026-07-15 17:24:45.777575
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '97e57bca510f'
down_revision = '3c46fe6af036'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite doesn't support ALTER TABLE DROP CONSTRAINT, so rebuild the table.
    op.execute("""
        CREATE TABLE video_uploads_new (
            id VARCHAR(32) NOT NULL,
            video_id VARCHAR(128) NOT NULL,
            tiktok_handle VARCHAR(128) NOT NULL,
            storage_key VARCHAR(512) NOT NULL,
            mime_type VARCHAR(128) NOT NULL,
            file_size INTEGER NOT NULL,
            original_filename VARCHAR(255) NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            position INTEGER DEFAULT '0' NOT NULL,
            PRIMARY KEY (id)
        )
    """)
    op.execute(
        "INSERT INTO video_uploads_new "
        "SELECT id, video_id, tiktok_handle, storage_key, mime_type, "
        "file_size, original_filename, created_at, updated_at, 0 "
        "FROM video_uploads"
    )
    op.execute("DROP TABLE video_uploads")
    op.execute("ALTER TABLE video_uploads_new RENAME TO video_uploads")
    op.create_index(op.f('ix_video_uploads_video_id'), 'video_uploads', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_uploads_tiktok_handle'), 'video_uploads', ['tiktok_handle'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_uploads_video_id'), table_name='video_uploads')
    op.create_index(op.f('ix_video_uploads_video_id'), 'video_uploads', ['video_id'], unique=1)
    op.drop_column('video_uploads', 'position')
    # ### end Alembic commands ###
